name: WASM

on:
  pull_request:
    paths: [wasm/**]
  push:
    paths: [wasm/**]

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install wasm-pack
        run: which wasm-pack >/dev/null 2>&1 || cargo install wasm-pack

      - name: Install ckb-debugger
        run: which ckb-debugger >/dev/null 2>&1 || cargo install ckb-debugger

      - name: wasm-test
        run: cd wasm && make check

      - name: wasm-test
        run: cd wasm && make test

      - name: build-web
        run: cd wasm && make build-web
